"""initial private multiuser schema"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '8645ff693793'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('initialized', sa.Boolean(), nullable=False),
    sa.Column('deletion_pending', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('institution', sa.Enum('banco_de_chile', 'banco_santander', 'copecpay', 'mercadopago', 'banco_estado', 'banco_falabella', name='institutioncode', native_enum=False), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_last4', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.Column('currency', sa.Enum('CLP', name='currencycode', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'id', name='uq_accounts_owner_id')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('income', 'expense', 'transfer', name='categorytype', native_enum=False), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id', 'parent_id'], ['categories.user_id', 'categories.id'], name='fk_categories_parent_id_owner'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'id', name='uq_categories_owner_id')
    )
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_table('categorization_rules',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id', 'category_id'], ['categories.user_id', 'categories.id'], name='fk_categorization_rules_category_id_owner'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'id', name='uq_categorization_rules_owner_id')
    )
    op.create_index(op.f('ix_categorization_rules_keyword'), 'categorization_rules', ['keyword'], unique=False)
    op.create_index(op.f('ix_categorization_rules_user_id'), 'categorization_rules', ['user_id'], unique=False)
    op.create_table('statements',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_checksum', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('period_month', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processed', 'failed', name='statementstatus', native_enum=False), nullable=False),
    sa.Column('raw_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id', 'account_id'], ['accounts.user_id', 'accounts.id'], name='fk_statements_account_id_owner'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', 'file_checksum', name='uq_statement_owner_checksum'),
    sa.UniqueConstraint('user_id', 'id', 'account_id', name='uq_statement_owner_account'),
    sa.UniqueConstraint('user_id', 'id', name='uq_statements_owner_id')
    )
    op.create_index(op.f('ix_statements_period_month'), 'statements', ['period_month'], unique=False)
    op.create_index(op.f('ix_statements_status'), 'statements', ['status'], unique=False)
    op.create_index(op.f('ix_statements_uploaded_at'), 'statements', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_statements_user_id'), 'statements', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_clp', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('income', 'expense', name='transactiontype', native_enum=False), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_source', sa.Enum('rule', 'manual', 'default', name='categorysource', native_enum=False), nullable=True),
    sa.Column('rule_id_applied', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['rule_id_applied'], ['categorization_rules.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.ForeignKeyConstraint(['user_id', 'account_id'], ['accounts.user_id', 'accounts.id'], name='fk_transactions_account_id_owner'),
    sa.ForeignKeyConstraint(['user_id', 'category_id'], ['categories.user_id', 'categories.id'], name='fk_transactions_category_id_owner'),
    sa.ForeignKeyConstraint(['user_id', 'rule_id_applied'], ['categorization_rules.user_id', 'categorization_rules.id'], name='fk_transactions_rule_id_applied_owner'),
    sa.ForeignKeyConstraint(['user_id', 'statement_id', 'account_id'], ['statements.user_id', 'statements.id', 'statements.account_id'], name='fk_transaction_statement_account'),
    sa.ForeignKeyConstraint(['user_id', 'statement_id'], ['statements.user_id', 'statements.id'], name='fk_transactions_statement_id_owner'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'id', name='uq_transactions_owner_id')
    )
    op.create_index('ix_transaction_owner_date', 'transactions', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_fingerprint'), 'transactions', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_transactions_normalized_description'), 'transactions', ['normalized_description'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('internal_transfer_matches',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outgoing_transaction_id', sa.Integer(), nullable=False),
    sa.Column('incoming_transaction_id', sa.Integer(), nullable=False),
    sa.Column('amount_clp', sa.Integer(), nullable=False),
    sa.Column('date_gap_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incoming_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['outgoing_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id', 'incoming_transaction_id'], ['transactions.user_id', 'transactions.id'], name='fk_internal_transfer_matches_incoming_transaction_id_owner'),
    sa.ForeignKeyConstraint(['user_id', 'outgoing_transaction_id'], ['transactions.user_id', 'transactions.id'], name='fk_internal_transfer_matches_outgoing_transaction_id_owner'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incoming_transaction_id', name='uq_internal_transfer_incoming_transaction'),
    sa.UniqueConstraint('outgoing_transaction_id', name='uq_internal_transfer_outgoing_transaction'),
    sa.UniqueConstraint('user_id', 'id', name='uq_internal_transfer_matches_owner_id')
    )
    op.create_index(op.f('ix_internal_transfer_matches_incoming_transaction_id'), 'internal_transfer_matches', ['incoming_transaction_id'], unique=False)
    op.create_index(op.f('ix_internal_transfer_matches_outgoing_transaction_id'), 'internal_transfer_matches', ['outgoing_transaction_id'], unique=False)
    op.create_index(op.f('ix_internal_transfer_matches_user_id'), 'internal_transfer_matches', ['user_id'], unique=False)
    # ### end Alembic commands ###

    op.execute("CREATE UNIQUE INDEX uq_category_owner_name ON categories (user_id, COALESCE(parent_id, -1), lower(trim(name)))")
    if op.get_bind().dialect.name == "postgresql":
        op.execute("REVOKE ALL ON SCHEMA finance FROM PUBLIC")
        op.execute("REVOKE ALL ON ALL TABLES IN SCHEMA finance FROM PUBLIC")
        op.execute("""DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
            REVOKE ALL ON SCHEMA finance FROM anon;
            REVOKE ALL ON ALL TABLES IN SCHEMA finance FROM anon;
          END IF;
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
            REVOKE ALL ON SCHEMA finance FROM authenticated;
            REVOKE ALL ON ALL TABLES IN SCHEMA finance FROM authenticated;
          END IF;
        END $$""")


def downgrade():
    op.drop_index("uq_category_owner_name", table_name="categories")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internal_transfer_matches_user_id'), table_name='internal_transfer_matches')
    op.drop_index(op.f('ix_internal_transfer_matches_outgoing_transaction_id'), table_name='internal_transfer_matches')
    op.drop_index(op.f('ix_internal_transfer_matches_incoming_transaction_id'), table_name='internal_transfer_matches')
    op.drop_table('internal_transfer_matches')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_normalized_description'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_fingerprint'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_index('ix_transaction_owner_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_statements_user_id'), table_name='statements')
    op.drop_index(op.f('ix_statements_uploaded_at'), table_name='statements')
    op.drop_index(op.f('ix_statements_status'), table_name='statements')
    op.drop_index(op.f('ix_statements_period_month'), table_name='statements')
    op.drop_table('statements')
    op.drop_index(op.f('ix_categorization_rules_user_id'), table_name='categorization_rules')
    op.drop_index(op.f('ix_categorization_rules_keyword'), table_name='categorization_rules')
    op.drop_table('categorization_rules')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
